import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'

import { sensorMap } from '../utils/const';

const fetcher = (...args) => fetch(...args).then(res => res.json())

const useSensors = () => {
  const { data, error } = useSWR('/api/weatherlink', fetcher);

  return {
    sensors: data,
    isLoading: !error && !data,
    isError: error
  }
}

export default function Home() {
  const { sensors, isLoading, isError } = useSensors('/api/weatherlink', fetcher)
  const [mainSensor, setMainSensor] = useState(null);

  useEffect(() => {
    if (sensors) {
      setMainSensor(sensors.sensors.find((sensor) => sensor.lsid === sensorMap.MAIN ).data[0]);
      console.log(mainSensor);
    }
  }, [sensors]);

  return (
    <div className={styles.container}>
      <Head>
        <title>#aq Weather</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        {mainSensor ? (
          <div>
            <h1>Current Conditions in #aq</h1>
            <ul>
              <li>Temperature: {mainSensor.temp}<br />(but it feels like {mainSensor.heat_index}°)</li>
              <li>Humidity: {mainSensor.hum}%</li>
            </ul>
          </div>
        ) : (
          <h1>Hang Tight</h1>
        )}
      </div>
    </div>
  )
}
