import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import useSWR from 'swr'

import Reading from '../components/Reading/Reading';
import Wind from '../components/Wind/Wind';
import { sensorMap } from '../utils/const';

const fetcher = (...args) => fetch(...args).then(res => res.json())

const useSensors = () => {
  const { data, error } = useSWR('/api/weatherlink', fetcher);

  return {
    sensors: data,
    isLoading: !error && !data,
    isError: error
  }
}

export default function Home() {
  const { sensors, isLoading, isError } = useSensors('/api/weatherlink', fetcher)
  const [mainSensor, setMainSensor] = useState(null);

  useEffect(() => {
    if (sensors) {
      setMainSensor(sensors.sensors.find((sensor) => sensor.lsid === sensorMap.MAIN ).data[0]);
      console.log(mainSensor);
    }
  }, [sensors]);

  return (
    <div className={styles.container}>
      <Head>
        <title>#aq Weather</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Current Conditions in #aq</h1>
      
      {mainSensor ? (
        <div className={styles.main}>
          <Reading title="Temp" value={`${mainSensor.temp}°`} />
          <Reading title="Feels Like" value={`${mainSensor.heat_index}°`} />
          <Reading title="Humidity" value={`${mainSensor.hum}%`} />
          <Reading title="Wind">
            <Wind windData={mainSensor} />
          </Reading>
        </div>
      ) : (
        <h1>Hang Tight</h1>
      )}
    </div>
  )
}
